"""Add presentation, slides, audio, cache tables

Revision ID: ebf8fd082fd7
Revises: c89990881f55
Create Date: 2025-10-16 01:06:32.126859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebf8fd082fd7'
down_revision: Union[str, Sequence[str], None] = 'c89990881f55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_id'), 'processing_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_job_id'), 'processing_jobs', ['job_id'], unique=True)
    op.create_table('tts_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('voice', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('pitch', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tts_cache_content_hash'), 'tts_cache', ['content_hash'], unique=False)
    op.create_index(op.f('ix_tts_cache_id'), 'tts_cache', ['id'], unique=False)
    op.create_table('api_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_time', sa.Float(), nullable=False),
    sa.Column('request_size', sa.Integer(), nullable=True),
    sa.Column('response_size', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_usage_created_at'), 'api_usage', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_usage_endpoint'), 'api_usage', ['endpoint'], unique=False)
    op.create_index(op.f('ix_api_usage_id'), 'api_usage', ['id'], unique=False)
    op.create_index(op.f('ix_api_usage_user_id'), 'api_usage', ['user_id'], unique=False)
    op.create_table('presentations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('slide_count', sa.Integer(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('presentation_metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presentations_id'), 'presentations', ['id'], unique=False)
    op.create_index(op.f('ix_presentations_user_id'), 'presentations', ['user_id'], unique=False)
    op.create_table('refinement_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('refined_text', sa.Text(), nullable=False),
    sa.Column('refinement_type', sa.Enum('GRAMMAR', 'STYLE', 'TONE', 'CLARITY', 'FORMALITY', name='textrefinementtype'), nullable=False),
    sa.Column('target_audience', sa.String(length=100), nullable=True),
    sa.Column('tone', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refinement_cache_content_hash'), 'refinement_cache', ['content_hash'], unique=False)
    op.create_index(op.f('ix_refinement_cache_id'), 'refinement_cache', ['id'], unique=False)
    op.create_index(op.f('ix_refinement_cache_user_id'), 'refinement_cache', ['user_id'], unique=False)
    op.create_table('exports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presentation_id', sa.Integer(), nullable=False),
    sa.Column('export_id', sa.String(length=100), nullable=False),
    sa.Column('export_format', sa.Enum('MP4', 'PPTX', 'AUDIO_MP3', 'AUDIO_WAV', name='exportformat'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('download_url', sa.String(length=500), nullable=True),
    sa.Column('include_audio', sa.Boolean(), nullable=True),
    sa.Column('include_subtitles', sa.Boolean(), nullable=True),
    sa.Column('quality', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exports_export_id'), 'exports', ['export_id'], unique=True)
    op.create_index(op.f('ix_exports_id'), 'exports', ['id'], unique=False)
    op.create_index(op.f('ix_exports_presentation_id'), 'exports', ['presentation_id'], unique=False)
    op.create_table('slides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presentation_id', sa.Integer(), nullable=False),
    sa.Column('slide_number', sa.Integer(), nullable=False),
    sa.Column('slide_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('original_content', sa.Text(), nullable=True),
    sa.Column('layout', sa.String(length=100), nullable=True),
    sa.Column('animations', sa.JSON(), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slides_id'), 'slides', ['id'], unique=False)
    op.create_index(op.f('ix_slides_presentation_id'), 'slides', ['presentation_id'], unique=False)
    op.create_table('audio_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slide_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=True),
    sa.Column('voice', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('pitch', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['slide_id'], ['slides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_files_id'), 'audio_files', ['id'], unique=False)
    op.create_index(op.f('ix_audio_files_slide_id'), 'audio_files', ['slide_id'], unique=False)
    op.create_table('subtitles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slide_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('format', sa.String(length=10), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('segments', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['slide_id'], ['slides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtitles_id'), 'subtitles', ['id'], unique=False)
    op.create_index(op.f('ix_subtitles_slide_id'), 'subtitles', ['slide_id'], unique=False)
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('preferences', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'preferences')
    op.drop_column('users', 'full_name')
    op.drop_index(op.f('ix_subtitles_slide_id'), table_name='subtitles')
    op.drop_index(op.f('ix_subtitles_id'), table_name='subtitles')
    op.drop_table('subtitles')
    op.drop_index(op.f('ix_audio_files_slide_id'), table_name='audio_files')
    op.drop_index(op.f('ix_audio_files_id'), table_name='audio_files')
    op.drop_table('audio_files')
    op.drop_index(op.f('ix_slides_presentation_id'), table_name='slides')
    op.drop_index(op.f('ix_slides_id'), table_name='slides')
    op.drop_table('slides')
    op.drop_index(op.f('ix_exports_presentation_id'), table_name='exports')
    op.drop_index(op.f('ix_exports_id'), table_name='exports')
    op.drop_index(op.f('ix_exports_export_id'), table_name='exports')
    op.drop_table('exports')
    op.drop_index(op.f('ix_refinement_cache_user_id'), table_name='refinement_cache')
    op.drop_index(op.f('ix_refinement_cache_id'), table_name='refinement_cache')
    op.drop_index(op.f('ix_refinement_cache_content_hash'), table_name='refinement_cache')
    op.drop_table('refinement_cache')
    op.drop_index(op.f('ix_presentations_user_id'), table_name='presentations')
    op.drop_index(op.f('ix_presentations_id'), table_name='presentations')
    op.drop_table('presentations')
    op.drop_index(op.f('ix_api_usage_user_id'), table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_id'), table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_endpoint'), table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_created_at'), table_name='api_usage')
    op.drop_table('api_usage')
    op.drop_index(op.f('ix_tts_cache_id'), table_name='tts_cache')
    op.drop_index(op.f('ix_tts_cache_content_hash'), table_name='tts_cache')
    op.drop_table('tts_cache')
    op.drop_index(op.f('ix_processing_jobs_job_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    # ### end Alembic commands ###
